### ISSUE TITLE
Gradient accumulation?

### ISSUE THREAD

**Issue by cmh1027** [xiaobiaodu/MVGS#1]
Hello, it seems your code triggers out-of-memory error in RTX3090. Maybe it is due to saving gradients of 6 images altogether. Isn't it better to accumulate gradient, backwarding each image for each sub-iteration?

**Comment by xiaobiaodu** [comment]
Hi. Thank you for your interest in our work. Out-of-memory error can be fixed by decreasing resolution or mv value. As for the mentioned accumulating gradient, we haven't tried it before.
