### ISSUE TITLE
MV_normal和MV_largest的意思

### ISSUE THREAD

**Issue by booker-max** [xiaobiaodu/MVGS#10]
在 run_360.py中，存在
![image](https://github.com/user-attachments/assets/eae979ad-a701-450d-acd7-25b6822df72d)
![image](https://github.com/user-attachments/assets/32fe48ad-51b8-44fe-9e8d-8615b570fdd7)
想问下这个是表示什么，是和场景相关的么

**Comment by xiaobiaodu** [comment]
Hi. There are no particular meanings. High mv values require more GPU memory and may lead to the overfitting problem. You can choose appropriate mv value in your application.
