### ISSUE TITLE
about the default params self.mv = 1

### ISSUE THREAD

**Issue by cv-lab-x** [xiaobiaodu/MVGS#11]
hi, thanks for your great work, as you mentioned in your paper multi-view training, but the default mv is 1, what params should be set to get better results eg:better psnr ? 
Looking forward to your reply, thanks. @xiaobiaodu

**Comment by xiaobiaodu** [comment]
Hi

Thanks for your interest in our work. You can use mv as 6 or 8 to obtain better psnr.
