### ISSUE TITLE
Can this algorithm train 4dgs

### ISSUE THREAD

**Issue by WangWenShan1** [xiaobiaodu/MVGS#13]
Hello, after the experiment, the algorithm has shown a significant improvement in performance. I saw a comparison of 4dgs in the paper. Can this algorithm train 4dgs?

**Comment by xiaobiaodu** [comment]
Hi, the current code is only for 3DGS. We will release 4DGS integrated with our MVGS in the future.

**Comment by chenj02** [comment]
> Hi, the current code is only for 3DGS. We will release 4DGS integrated with our MVGS in the future.

hello，I have a question：how can MVGS used in 4DGS if the scene is dynamic？The camera at different time seems not able to constraint the Gaussian because of the motion in the scene？
