### ISSUE TITLE
Question regarding table

### ISSUE THREAD

**Issue by cmh1027** [xiaobiaodu/MVGS#14]
![image](https://github.com/user-attachments/assets/6a740bce-78c4-4f29-a093-3ce85dcdb0b1)
This is the table inyour paper

![image](https://github.com/user-attachments/assets/0fbc6e0b-142a-44ed-a0bb-14813bd69745)
and this is the table in 3D Gaussian Splatting as Markov Chain Monte Carlo (NeurIPS 2024)

I tested 3DGS from  official repo, and I got the result similar to the one in 3DGS-MCMC. Metrics in your paper are too low. Can you share the experiments settings?

**Comment by xiaobiaodu** [comment]
Hi, The results of 3DGS in our paper are from Scafold-GS. We directly use their results.
