### ISSUE TITLE
reproduce Tanks&Temples results

### ISSUE THREAD

**Issue by cv-lab-x** [xiaobiaodu/MVGS#15]
hi, thanks for your great work, what's your configs to train Tanks&Temples results, it seems to out of mem on 80GB gpu. 
Looking forward to your reply, thanks. @xiaobiaodu

**Comment by xiaobiaodu** [comment]
Hi. You can try to decrease the mv value as we claim in Readme.

**Comment by cv-lab-x** [comment]
> Hi. You can try to decrease the mv value as we claim in Readme.

thanks for your quick reply, i want to reproduce the results in your paper, so the scripts to reproduce the tanks&Temples resuls in your paperis : `python train.py -s  {data_path}   --eval --white_background  -m {save_path}  --mv  6  ` ?

**Comment by xiaobiaodu** [comment]
Yes. You can try it. If the OOM problem happens, you can further decrease the mv value.

**Comment by xiaobiaodu** [comment]
By the way, for the unbounded scenes, our method needs more GPU memory.
