### ISSUE TITLE
results on Mip-NeRF 360 datasets

### ISSUE THREAD

**Issue by cv-lab-x** [xiaobiaodu/MVGS#16]
hi, thanks for your work, some little questions about the indoor and outdoor results on mipnerf360. the results on stump, garden, bicycle seem lower than origin 3dgs after using this work, did you analyze the reasons?
Looking forward to your reply, thanks. @xiaobiaodu

**Comment by xiaobiaodu** [comment]
Hi.

Thanks for your question. It is a very interesting phenomenon in our work. Particularly, we found our method less effective in scenes not capturing objects in 360 degrees.  In addition, to the unbounded scenes, our method also has this drawback. There might be some overfitting problems in our method itself, like training with server overlapping regions. Hopefully, we are committing to design a next-generation multi-view method to solve this problem.
