### ISSUE TITLE
Code and experimental performance issues

### ISSUE THREAD

**Issue by Carloslius** [xiaobiaodu/MVGS#17]
Thank you very much for your excellent ideas and contributions. I have two questions about the code.
1.  In the following function, should box1 = boxes[j] be box1 = boxes[i+1+j]? I think this is consistent with the intersection of the areas with the greatest loss in two adjacent frames mentioned in the paper.
```
def densify_and_prune(self, max_grad, min_opacity, extent, max_screen_size, cams, boxes):
        grads = self.xyz_gradient_accum / self.denom
        grads[grads.isnan()] = 0.0
        box3ds = []
        if cams is not None:
            for i, cam_0 in enumerate(cams):
                for j, cam_1 in enumerate(cams[i+1:]):
                    ray0_o = cam_0.rayo
                    ray0_d = cam_0.rayd
                    box0 = boxes[i]
                    ray1_o = cam_1.rayo
                    ray1_d = cam_1.rayd
                    box1 = boxes[j]
```
2. In addition, why do I get so few points in the space with the largest loss during my experiment? Even if I calculate the mask of Gaussian points, there are usually only a few points in the mask.

**Comment by xiaobiaodu** [comment]
Thank you for pointing out this problem. We will fix it.
