### ISSUE TITLE
Is this version the 3DGS version？

### ISSUE THREAD

**Issue by EleZou** [xiaobiaodu/MVGS#2]

**Comment by xiaobiaodu** [comment]
Yes

**Comment by EleZou** [comment]
Thank you very much for your innovative and thoughtful work. Do you have any plans to open-source other optimized versions, such as (Scaffold-GS)?

**Comment by xiaobiaodu** [comment]
Thank you for your interest in our work. We currently don't have plans to release the Scaffold-GS version. Maybe we will release it after our paper is accepted.

**Comment by EleZou** [comment]
I fully understand your decision and wish you success in getting your outstanding work accepted smoothly.
