### ISSUE TITLE
About CROSS-INTRINSIC GUIDANCE

### ISSUE THREAD

**Issue by PoplarPoplar** [xiaobiaodu/MVGS#20]
Dear Author,

I hope this message finds you well. I have been reviewing your code and noticed that the set_rays function in utils/camera_utils.py is not referenced anywhere. In train.py, I found a call to the set_rays_od function, but not to set_rays. Could you please clarify this situation for me?

Additionally, I would like to inquire about the specific implementation of the CROSS-INTRINSIC GUIDANCE step in the code, as I have been unable to locate it. I apologize for any inconvenience this may cause.

Thank you very much for your time and assistance.

Best regards
@xiaobiaodu

**Comment by Wangjiaju0811CQU** [comment]
I also have this question。@xiaobiaodu

**Comment by xiaobiaodu** [comment]
Hi @PoplarPoplar @HENUwjj 

CROSS-INTRINSIC GUIDANCE can be easily implemented by our "run_360.py"

**Comment by PoplarPoplar** [comment]
thankyou
