### ISSUE TITLE
Batch traning for multiview using Grendel-GS

### ISSUE THREAD

**Issue by Gaozhongpai** [xiaobiaodu/MVGS#3]
Hi, thanks for sharing the code. The current implementation for multiview training is really slow. Do you plan to use Grendel-GS (https://github.com/nyu-systems/Grendel-GS) to speed up the training?

**Comment by xiaobiaodu** [comment]
Thank you for sharing Grendel-GS. The training time problem is very significant and we are finding a solution to deal with it.

**Comment by Gaozhongpai** [comment]
The multiview consistency is indeed very useful, especially for our new work 6DGS: https://arxiv.org/abs/2410.04974 (I tried last night and PSNR boosts 2 dB).

**Comment by xiaobiaodu** [comment]
Thank you for your recognition for our work. Please consider utilizing and citing our work in your paper.





------------------ Original ------------------
From: Zhongpai Gao ***@***.***&gt;
Date: Wed, Oct 9, 2024 1:03 AM
To: xiaobiaodu/MVGS ***@***.***&gt;
Cc: Xiaobiao Du ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [xiaobiaodu/MVGS] Batch traning for multiview using Grendel-GS(Issue #3)





 
The multiview consistency is indeed very useful, especially for our new work 6DGS: https://arxiv.org/abs/2410.04974.

**Comment by Gaozhongpai** [comment]
> Thank you for your recognition for our work. Please consider utilizing and citing our work in your paper.

We consider integrating your work into our 6DGS in the appendix or journal extension, where we will cite your work.
