### ISSUE TITLE
Questions about multi-view augmented densification

### ISSUE THREAD

**Issue by Tompson11** [xiaobiaodu/MVGS#4]
Thank you for sharing your work!
I've noticed that in your implementation, the threshold for multi-view augmented densification is calculated only by training cameras in the densification iteration. I wonder if it is better than using all training cameras from iterations between two densifications;

                    diffs = []
                    for i, cam1 in enumerate(camera_t):
                        for j, cam2 in enumerate(camera_t):
                            if i == j:
                                continue
                            else:
                                diff = torch.sqrt(torch.sum((cam1 - cam2)**2))
                                diffs.append(diff)
                    diffs = torch.stack(diffs)
                    if torch.any(diffs > 1):
                        densify_t = opt.densify_grad_threshold * 0.5
                    else:
                        densify_t = opt.densify_grad_threshold

here camera_t is cleared after each iteration

**Comment by xiaobiaodu** [comment]
Hi. Thanks for your interest in our work. I guess using all training cameras would lead to the densification threshold being half of the original threshold. It may lead to an overfitting problem since it always densifies in a lower threshold.
