### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by LaFeuilleMorte** [xiaobiaodu/MVGS#5]
File "train.py", line 280, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 111, in training
    total_loss.backward()
  File "/aistudio/workspace/system-default/envs/mvgs/lib/python3.7/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/aistudio/workspace/system-default/envs/mvgs/lib/python3.7/site-packages/torch/autograd/__init__.py", line 175, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
RuntimeError: Function _RasterizeGaussiansBackward returned an invalid gradient at index 2 - got [0, 0, 3] but expected shape compatible with [0, 16, 3]

My cmd is :
python train.py -s  {xxx}  --eval --white_background  -m  {xxx}  --mv  12  -r 1

**Comment by xiaobiaodu** [comment]
Did you modify our code?

**Comment by LaFeuilleMorte** [comment]
> Did you modify our code?

Never mind. I've solved this problem. It may due to the rasterizer. I use another version of it.

**Comment by LaFeuilleMorte** [comment]
> > Did you modify our code?
> 
> Never mind. I've solved this problem. It may due to the rasterizer. I use another version of it.

BTW, the training speed seemed to be 1/ mv (mv = batch size) of the original GS, which will become a significant problem when utilizing this method. Do you have any tips on how to reduce the training time and memory?

**Comment by xiaobiaodu** [comment]
We are addressing this problem. Once we have progress, we will update our GitHub.
