### ISSUE TITLE
out of memory error

### ISSUE THREAD

**Issue by ansj11** [xiaobiaodu/MVGS#6]
I ran the first stage and got an error, the memory almost increased to 500GB. my data have 62 images. Do you know the reason?
`Loading Test Cameras [10/10 13:20:59]
 Number of points at initialisation :  8951 [10/10 13:21:00]
 Traceback (most recent call last):
   File "/gemini/data-1/MVGS/train.py", line 281, in <module>
     training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
   File "/gemini/data-1/MVGS/train.py", line 38, in training
     scene = Scene(dataset, gaussians)
   File "/gemini/data-1/MVGS/scene/__init__.py", line 83, in __init__
     self.gaussians.create_from_pcd(scene_info.point_cloud, self.cameras_extent)
   File "/gemini/data-1/MVGS/scene/gaussian_model.py", line 134, in create_from_pcd
     dist2 = torch.clamp_min(distCUDA2(torch.from_numpy(np.asarray(pcd.points)).float().cuda()), 0.0000001)
 MemoryError: std::bad_alloc: cudaErrorMemoryAllocation: out of memory`

<img width="392" alt="截屏2024-10-10 13 25 49" src="https://github.com/user-attachments/assets/8ef740a8-ae93-43e0-9e68-d981f60913f7">

**Comment by xiaobiaodu** [comment]
Hi

Please try this command We've claimed in Readme.
```
python train.py -s  {data_path}   --eval --white_background  -m {save_path}  --mv  6  
```

**Comment by ansj11** [comment]
thank you for your quick reply! I wonder if it is necessary to run 4 stages with this command？

**Comment by xiaobiaodu** [comment]
Yes. 4-stage training can bring huge improvement, but I guess the resolution of your training images is too large, please consider training on smaller resolutions.

**Comment by ansj11** [comment]
thank you very much! My training images size is 1600x1200.
