### ISSUE TITLE
black render image 

### ISSUE THREAD

**Issue by ansj11** [xiaobiaodu/MVGS#7]
I trained 62 car images with mask, but the final rendering result seems abnormal with black cloud, do you know the reason?

![00001](https://github.com/user-attachments/assets/34a9af0c-fe6f-4459-bdbb-99f60ac00a85)
![00001r](https://github.com/user-attachments/assets/0efb0ead-e1f8-49f3-8003-face6a076ce8)

**Comment by xiaobiaodu** [comment]
Hi. Please try to decrease mv value in the training command. It may be overfitting with too many training views at a training iteration.
